# Generated by Django 5.0.7 on 2024-07-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='messege',
            new_name='message',
        ),
    ]
